function rankTeams(votes) {
    var hash = {};
    for (var i = 0; i < votes[0].length; i++) {
        hash[votes[0][i]] = [];
        for (var j = 0; j < votes[0].length; j++) {
            hash[votes[0][i]][j] = 0;
        }
    }
    for (var i = 0; i < votes.length; i++) {
        for (var j = 0; j < votes[i].length; j++) {
            hash[votes[i][j]][j] = (hash[votes[i][j]][j] || 0) + 1;
            // console.log(votes[i][j], hash[votes[i][j]], hash[votes[i][j]][j]);
        }
    }
    var res = Object.entries(hash).sort(function (a, b) {
        for (var i = 0; i < a[1].length; i++) {
            if (a[1][i] > b[1][i]) {
                return -1;
            }
            else if (a[1][i] < b[1][i]) {
                return 1;
            }
        }
        if (a[0] > b[0])
            return 1;
        return -1;
    });
    // console.log(hash);
    console.log(res);
    return res.map(function (el) { return el[0]; }).join('');
}
;
var res = rankTeams(["XDELQOKZUGMCBTWAJNPFRVIS", "IQKGUDCWMNLSABZEPVXFJRTO", "SFPUJWZABNRLQEMXKIGDVCTO", "FISQWOZAGXJDNLTKPRECVUBM", "BMXIRQOWJSLPDNGAEFKZTUVC", "SCUFTIAQMWNXBGZEOJVDLKRP", "LMNXWKDBTAGPFUCJSROIQZEV", "NVDICPQFBZLRGWTMXJOAUESK", "PGZRUWNFMKTVJSLCDEXOABIQ", "BFKNDXRIGWTVSUJOCMPZAEQL", "MJLDKRNWPQXUFSTEGCOBVAIZ", "VCIMLFJSPZTDRKBAGXWUOEQN", "TERGMVDPILNQSFJCAKZWXBOU", "KOPFCIDQSVAMRBLNTWUZXJGE", "NKWPJGUAFOTZIERXMSLBDCQV", "QUKLSIFCDVZEAMXGJNTWROPB", "DSAGZRFWTMJEILKOPUNQVXCB", "ARQIVZNCMBJGWUPKEOSLFTDX", "ESMATLNJKPRFGXWVUCOQDIZB", "QNGTVDFICPSKMWUJBOZELAXR", "JAOMTSGFQPDWKRNLUXEVBCIZ", "FORAQBEDSTNPUZICVXGWMKLJ", "UWAFSXITRMPEGVQDLZBCNJOK", "IKFOVMNWJLCZBUAGERQPXTSD", "SLEOPWNDBUVIGQJZMRACXTFK", "GTDKMOJSILNAVXFPZQCUWRBE", "AZGRVFJDEUSCNLTBXWQIPMOK", "VQPNUMCJKSBXWIAFTGDOEZRL", "PVNODUXIMJSGACQTWRFBKLZE", "QGKDUAIMEVTXSZFBJLOWNPRC", "MDUOXBVQJPSAGNIKLRFZTCWE", "FMRTEDKWPVLGBICXSNZAQJOU", "WUEFMGXSIRNAOPCBDLQTKJZV", "UDGSPEQVZOBMNICJKXTWALRF", "SFNWLTARVKPJQZMGUDBOICEX", "FSPCMAJZEKNRLDWBGOXQIUVT", "VRUOAMJQGFSIZNXLEPWTDCBK", "VNCMBRLKUPDISJEWOAZGTXFQ", "VGJQZXMPKEIRLTNODCABWFSU", "IMALJVBCXSQPOUGEKNTRFDWZ", "UPJBVKQOAIDGWEZRLTNSXFMC", "IUAPCZFWOQTXBSNLKGVRDMEJ", "DOIRNGMKJLEUCPTWZQSVXFAB", "VJMWTPZFOGBNIDCQAULERKSX", "OAISKWCDLVRQFGNZPUTJEMXB", "NBTGWMEUROJDCKAZLFQXISPV", "DSOBAIJXFWNTUVERGQMCLKPZ", "SBLFZOGCNDWPXAEKTVRJUMIQ", "EKWMAQNURJBZPLFDSGOVIXCT", "BKXRSNVMWGAPCIFLZJTEUQOD", "VQNWJSZTCPEURAKBLIXOFGMD", "TQKFDXCWIUARVBELNOPJZGMS", "MSCPWBTKQUFVDGEXROANJLIZ", "XFQVITPRZMONWCLKBUAJGSED", "MVKLRFQWICOPDJBUSTXNEZGA", "DMKBRGLONJEIFTXZPUACQWSV", "NKSJBQZORVFTXWAUCDLGEMIP", "JQUIXNBRDMOLGSTFVAZCPEWK", "MEBXTJUNVWCQAZGRLIKSPDFO", "EKNUQILMTDPOSFJZWXGVCARB", "JOZNFECPVSXRLGDUKQWBITAM", "UXNZISEGTCVABJMKFLWDQPOR", "IJCFLPGZRXQUMANODKBVSETW", "KCJQRFEWNGAMBIXZVLPDSUTO", "TMSEDRAUWZGQXJPIFVLCOBKN", "ZPRXJNOEKCGFUSDQAILWMVTB", "WTBXANSJLRKFEPOIVDMQUZCG", "IRLVZNQPECOJATFWUSDMGKBX", "BGMPAZOIKWCSUDJNXLTVREQF", "BZXSTPRMLEKWCFIVONGADUQJ", "UFGZCWTARKSBDJXPMVQIENOL", "ZBROLDUFMNQAPJEGITXWCSKV", "FWLJXQDTRCGNVUZMAPBKISEO", "SJXLKAVZCPBIEWFQTNODGRMU", "VAIBDLOEXGUZQWMPNSJTCRKF", "XFLMPECKOQINGWSZJRTVBADU", "ZAJCPMSKUBFWEXQDTVGNLORI", "FUVECNMKZWJBGXTDLPASIOQR", "COFKSVMTNLBWXAREZDQIJUGP", "TKRVFXUIONEALPCDSJGBZWQM", "VJNQLTARZSGCPOMFBUWIXKDE", "GMUSFBPDZATKWEQONXCJILVR", "RFNCLTQZXMSVWPIUBGDEAKOJ", "NARSWLXMEIGQCFBOVDUJPZTK", "OBZVJGSKDUCXAQWPIFNEMTRL", "RIEQDWFSLCGTPKNBAJUVMZOX", "GBAXDSVUEOJNTLPIRKZCWQMF", "ZOETNALWVPGXRIMQKDBFUSCJ", "NAMBJKFZQTOSGWCDPIRXLEUV", "NWQJUZMKIXCGDSBREFPATLOV", "KWAECTUZODSPIJMNLVQRXFBG", "JXPWZNOCGRDKLQITUSEVAFBM", "FNAXSLPRWUBMQJICZTVKDOEG", "GMAWSUXVPZINTODEBRJFKQLC", "FACUKTLWNJSXRQMEDZVGBOIP", "FXEGPVLUJDRNQMTOWSIKAZCB", "ZNEKOJXDVQSUFARMLWPGICTB", "IRSZQGUKVJXCANFWLOBDEMPT", "IUEDPRJFVGQSAXNOWCBMZTLK", "XGKLOPJVQCWTBMSNUZARIEDF", "VSOJUPRFDCNQXTLMBKIGZWEA", "UDGIKPAFNTZWCJRMSLVOXEQB", "GQOIULRNMCJVPFEAZBSDWKTX", "ZJUTMKIFXRSCOPENVGLBDAQW", "ZUQOBCPWNJKVARLTDEGIXFSM", "ADBOKTGCWFMNVUEZLRPIQJSX", "ALDVEQZKCTOJRWBMISPNXFGU", "CEGUFDRXLAVTQNWOKMPZIJBS", "EMBXCVQDJLNWSGIZPRAFTUKO", "KJSQEPNOVGRWZLUIADFBCTXM", "UWVFQEDASJBGXCNPTZIORMLK", "XFLCZSMJAVEPIQDRTUBNKGWO", "URFBQMVATJWEPDCNGSILOZXK", "ZLDPUVIWOJEXGNTQFRBKSACM", "IEQBVDUPNLCGJASFRXTWZOMK", "TVWMROKSUPCXNFEALDQZIGBJ", "GFKEZOICNTXPASMBJVRUWLDQ", "NVWKLBMQJFPIRCSDOZGTXEAU", "QANRCGLPMDZKFOTXBVJEIWUS", "UPCLXNVQZTRKMEBGAOSFDJWI", "PANMJZIFCWGKQDXSRUETOLVB", "JGWVNUXLKAEODTBZIQRCMPFS", "TEOMUIZFSXPGWLADRBQKJVCN", "XPFDJLGZAWEKTRVCMBNUSOQI", "OCQSTRKAZPIMUBNDGEXJVWLF", "MILWTBRAVGZODFJUCSPXQENK", "FREBOSZDPMCNUJXAVKIGLWQT", "TQWPUCERNGIBMXDZKJVASFOL", "APLDRMWCQNFUTSKXVEGJIZBO", "SUWEMPJNFITABXVOCRZLDQKG", "FGRZBWMUTIACNEJKVQPXDOSL", "PBUWQEIDOLXCRNFVSZJTKAMG", "BRFZUGVLWEJKNIASPMTXDQOC", "XLIPMTZQSUFVANKOGBEJDRCW", "GSCRPUAKMEIDBVOLQXWZNFTJ", "KCQMJXRWSFGNBDLAUOTEIVZP", "GKDPJSRMALVEXUNWOICTFQZB"]);
console.log(res);
